import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Terraform deployment modules require hosted auth origin and provider guardrails", async () => {
  const terraformReadme = await readFile("deploy/terraform/README.md", "utf8");
  assert.match(terraformReadme, /aws\//);
  assert.match(terraformReadme, /gcp\//);
  assert.match(terraformReadme, /backend\.tf\.example/);
  assert.match(terraformReadme, /pin the OpenWiki image by digest/);
  assert.match(terraformReadme, /OPENWIKI_RUNTIME_MODE=hosted/);
  assert.match(terraformReadme, /OPENWIKI_PUBLIC_ORIGIN/);
  assert.match(terraformReadme, /OPENWIKI_REQUIRE_AUTH=true/);
  assert.match(terraformReadme, /OPENWIKI_TRUST_AUTH_HEADERS=1/);
  assert.match(terraformReadme, /x-openwiki-actor/);
  assert.match(terraformReadme, /Secrets Manager/);
  assert.match(terraformReadme, /Secret Manager/);
  assert.match(terraformReadme, /lifecycle policies/);
  assert.match(terraformReadme, /cloud-run-readmostly/);
  assert.match(terraformReadme, /GCS FUSE as production Git storage/);

  const awsTerraform = await readFile("deploy/terraform/aws/main.tf", "utf8");
  assert.match(awsTerraform, /aws_ecs_service/);
  assert.match(awsTerraform, /aws_ecs_service" "openwiki_worker"/);
  assert.match(awsTerraform, /aws_ecs_task_definition" "openwiki_worker"/);
  assert.match(awsTerraform, /OPENWIKI_BOOTSTRAP_MODE/);
  assert.match(awsTerraform, /Waiting for OpenWiki workspace bootstrap/);
  assert.match(awsTerraform, /aws_ecs_service\.openwiki/);
  assert.match(awsTerraform, /aws_efs_file_system/);
  assert.match(awsTerraform, /OPENWIKI_ROOT/);
  assert.match(awsTerraform, /OPENWIKI_RUNTIME_MODE/);
  assert.match(awsTerraform, /OPENWIKI_PUBLIC_ORIGIN/);
  assert.match(awsTerraform, /value = var\.public_origin/);
  assert.match(awsTerraform, /OPENWIKI_READ_BACKEND/);
  assert.match(awsTerraform, /OPENWIKI_SEARCH_BACKEND/);
  assert.match(awsTerraform, /OPENWIKI_QUEUE_BACKEND/);
  assert.match(awsTerraform, /OPENWIKI_OPERATIONAL_STATE_BACKEND/);
  assert.match(awsTerraform, /OPENWIKI_WRITE_COORDINATOR_BACKEND/);
  assert.match(awsTerraform, /DATABASE_URL/);
  assert.match(awsTerraform, /OPENWIKI_REQUIRE_AUTH/);
  assert.match(awsTerraform, /OPENWIKI_TRUST_AUTH_HEADERS/);
  assert.match(awsTerraform, /OPENWIKI_TRUST_AUTH_HEADERS_SECRET/);
  assert.match(awsTerraform, /\/readyz/);
  assert.match(awsTerraform, /port\s+= 443/);
  assert.match(awsTerraform, /protocol\s+= "HTTPS"/);
  assert.match(awsTerraform, /status_code = "HTTP_301"/);
  assert.match(awsTerraform, /production_guardrails/);
  assert.match(awsTerraform, /certificate_arn/);
  assert.match(awsTerraform, /@sha256:/);
  assert.match(awsTerraform, /aws_iam_role_policy" "execution_runtime_secrets"/);
  assert.match(awsTerraform, /ReadRuntimeSecrets/);
  assert.match(awsTerraform, /secretsmanager:GetSecretValue/);
  assert.match(awsTerraform, /ssm:GetParameters/);
  assert.match(awsTerraform, /kms:Decrypt/);
  assert.match(awsTerraform, /runtime_secret_kms_key_arns/);

  const awsVariables = await readFile("deploy/terraform/aws/variables.tf", "utf8");
  assert.match(awsVariables, /variable "certificate_arn"/);
  assert.match(awsVariables, /variable "worker_desired_count"/);
  assert.match(awsVariables, /variable "public_origin"/);
  assert.match(awsVariables, /variable "production_mode"/);
  assert.match(awsVariables, /variable "trusted_auth_headers_secret_arn"/);
  assert.match(awsVariables, /variable "database_url_secret_arn"/);
  assert.match(awsVariables, /variable "runtime_secret_kms_key_arns"/);
  assert.match(awsVariables, /default\s+= false/);

  const awsBackend = await readFile("deploy/terraform/aws/backend.tf.example", "utf8");
  assert.match(awsBackend, /backend "s3"/);
  const awsReadme = await readFile("deploy/terraform/aws/README.md", "utf8");
  assert.match(awsReadme, /aws-ecs-efs/);
  assert.match(awsReadme, /pin the OpenWiki image by digest/);
  assert.match(awsReadme, /ALB OIDC/);
  assert.match(awsReadme, /Secrets Manager/);
  assert.match(awsReadme, /trusted_auth_headers_secret_arn/);
  assert.match(awsReadme, /database_url_secret_arn/);
  assert.match(awsReadme, /runtime_secret_kms_key_arns/);
  assert.match(awsReadme, /customer-managed KMS key/);
  assert.match(awsReadme, /public_origin=https:\/\/wiki\.example\.com/);

  const gcpTerraform = await readFile("deploy/terraform/gcp/main.tf", "utf8");
  assert.match(gcpTerraform, /google_cloud_run_v2_service/);
  assert.match(gcpTerraform, /google_storage_bucket/);
  assert.match(gcpTerraform, /OPENWIKI_ROOT/);
  assert.match(gcpTerraform, /OPENWIKI_RUNTIME_MODE/);
  assert.match(gcpTerraform, /OPENWIKI_PUBLIC_ORIGIN/);
  assert.match(gcpTerraform, /local\.public_origin/);
  assert.match(gcpTerraform, /data\.google_project\.current\.number/);
  assert.match(gcpTerraform, /OPENWIKI_READ_BACKEND/);
  assert.match(gcpTerraform, /OPENWIKI_SEARCH_BACKEND/);
  assert.match(gcpTerraform, /OPENWIKI_QUEUE_BACKEND/);
  assert.match(gcpTerraform, /OPENWIKI_OPERATIONAL_STATE_BACKEND/);
  assert.match(gcpTerraform, /OPENWIKI_WRITE_COORDINATOR_BACKEND/);
  assert.match(gcpTerraform, /DATABASE_URL/);
  assert.match(gcpTerraform, /OPENWIKI_REQUIRE_AUTH/);
  assert.match(gcpTerraform, /OPENWIKI_TRUST_AUTH_HEADERS/);
  assert.match(gcpTerraform, /secret_key_ref/);
  assert.match(gcpTerraform, /\/data\/wiki/);
  assert.match(gcpTerraform, /google_artifact_registry_repository/);
  assert.match(gcpTerraform, /google_sql_database_instance/);
  assert.match(gcpTerraform, /connector_enforcement\s+= "REQUIRED"/);
  assert.match(gcpTerraform, /edition\s+= var\.sql_edition/);
  assert.match(gcpTerraform, /deletion_policy\s+= "ABANDON"/);
  assert.match(gcpTerraform, /cloud-sql-proxy/);
  assert.match(gcpTerraform, /--address=0\.0\.0\.0/);
  assert.match(gcpTerraform, /google_cloud_run_v2_job" "worker"/);
  assert.match(gcpTerraform, /google_cloud_run_v2_job" "rebuild"/);
  assert.match(gcpTerraform, /worker", "--once"/);
  assert.match(gcpTerraform, /db sync-postgres --full/);
  assert.match(gcpTerraform, /roles\/cloudsql\.client/);
  assert.match(gcpTerraform, /roles\/secretmanager\.secretAccessor/);
  assert.match(gcpTerraform, /roles\/artifactregistry\.writer/);
  assert.match(gcpTerraform, /google_billing_budget/);
  assert.match(gcpTerraform, /preview_guardrails/);
  assert.match(gcpTerraform, /!var\.allow_unauthenticated/);
  assert.match(gcpTerraform, /!var\.force_destroy_bucket/);
  assert.match(gcpTerraform, /var\.sql_backup_enabled/);
  assert.match(gcpTerraform, /var\.sql_deletion_protection/);
  const gcpVariables = await readFile("deploy/terraform/gcp/variables.tf", "utf8");
  assert.match(gcpVariables, /POSTGRES_16/);
  assert.match(gcpVariables, /db-f1-micro/);
  assert.match(gcpVariables, /ENTERPRISE/);
  assert.match(gcpVariables, /cloud-sql-proxy@sha256:/);
  assert.match(gcpVariables, /variable "billing_account_id"/);
  assert.match(gcpVariables, /variable "force_destroy_bucket"/);
  assert.match(gcpVariables, /default\s+= true/);
  const gcpBackend = await readFile("deploy/terraform/gcp/backend.tf.example", "utf8");
  assert.match(gcpBackend, /backend "gcs"/);
  const gcpReadme = await readFile("deploy/terraform/gcp/README.md", "utf8");
  assert.match(gcpReadme, /cloud-run-readmostly/);
  assert.match(gcpReadme, /not the\s+recommended writable Git backend/);
  assert.match(gcpReadme, /Cloud Storage\s+FUSE is not POSIX/);
  assert.match(gcpReadme, /gcp-gke/);
  assert.match(gcpReadme, /Cloud SQL Auth Proxy/);
  assert.match(gcpReadme, /worker job/);
  assert.match(gcpReadme, /rebuild\/sync job/);
  assert.match(gcpReadme, /Secret Manager/);
  assert.match(gcpReadme, /trusted_auth_headers_secret_name/);
  assert.match(gcpReadme, /database_url_secret_name/);
  assert.match(gcpReadme, /sql_backup_enabled=true/);
  assert.match(gcpReadme, /sql_deletion_protection=true/);
  assert.match(gcpReadme, /billing_account_id/);
  assert.match(gcpReadme, /--gcp-build-image/);

});
