export type {
  ChannelActorInput,
  ChannelBindingRecord,
  ChannelCursorUpdateResult,
  ChannelDeliveryRecord,
  ChannelIdentityRecord,
  ChannelInteractionRecord,
  ChannelSessionBindingRecord,
  CloudChannelDeliveryStatus,
  CloudChannelIdentityRole,
  CloudChannelIdentityStatus,
  CloudChannelProviderId,
  CloudChannelProviderKind,
  HeadlessAgentRecord,
  IssuedChannelInteractionRecord,
} from '../adapter.js'
