version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:40"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: pip
    directory: /docs
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docs

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker-compose
    directory: /deploy/compose
    schedule:
      interval: weekly
      day: monday
      time: "07:40"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: terraform
    directory: /deploy/terraform/aws
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform

  - package-ecosystem: terraform
    directory: /deploy/terraform/gcp
    schedule:
      interval: weekly
      day: monday
      time: "08:20"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform
