// AUTO-GENERATED by `node scripts/i18n-coverage.mjs --write-status` — do not edit.
// Honest translation coverage for the built-in non-English locale catalogs
// (they share one key set, so one figure covers all of them). Surfaced in
// the language picker; the i18n:check gate fails if this file drifts from
// the computed report.
export const BUILT_IN_TRANSLATION_COVERAGE = {
  translatedKeys: 437,
  totalStaticKeys: 1379,
} as const
