apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwiki-data
  labels:
    app.kubernetes.io/name: openwiki
    app.kubernetes.io/instance: openwiki
    app.kubernetes.io/part-of: openwiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
