import { READ_INBOX_TOOL_DEFINITIONS } from "./inbox-tool-definitions.ts";

export const READ_TOOL_DEFINITIONS = [
  {
    name: "wiki.search",
    title: "Search OpenWiki",
    description: "Search pages, sources, claims, facts, and takes in the OpenWiki workspace.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        query: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 50 },
        persona: { type: "string", enum: ["default", "researcher", "editor", "reviewer", "governance"] },
        types: { type: "array", items: { type: "string" } },
        mode: { type: "string", enum: ["lexical", "hybrid"] },
        fuzzy: { type: "boolean" },
        filters: {
          type: "object",
          additionalProperties: false,
          properties: {
            topics: { type: "array", items: { type: "string" } },
            status: { type: "array", items: { type: "string" } },
            updated_after: { type: "string" },
          },
        },
        offset: { type: "integer", minimum: 0 },
        include_highlights: { type: "boolean" },
        include_explain: { type: "boolean" },
      },
      required: ["query"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.recall",
    title: "Recall OpenWiki Memory",
    description: "Retrieve policy-visible facts, takes, claims, pages, and sources with a hot-memory summary.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        query: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 50 },
        types: { type: "array", items: { type: "string" } },
        include_explain: { type: "boolean" },
        include_highlights: { type: "boolean" },
      },
      required: ["query"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.ask",
    title: "Ask OpenWiki With Citations",
    description: "Answer a question using OpenWiki search results and cited records.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        question: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 20 },
        include_explain: { type: "boolean" },
      },
      required: ["question"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.think",
    title: "Think Through OpenWiki With Citations",
    description: "Synthesize an answer with cited OpenWiki evidence, gaps, and retrieval diagnostics.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        question: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 20 },
        include_explain: { type: "boolean" },
      },
      required: ["question"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_page",
    title: "Read OpenWiki Page",
    description: "Read an OpenWiki page by ID, URI, path, or slug.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_source",
    title: "Read OpenWiki Source",
    description: "Read an OpenWiki source record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        include_content: { type: "boolean" },
        max_bytes: { type: "integer", minimum: 0, maximum: 1048576 },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_claim",
    title: "Read OpenWiki Claim",
    description: "Read an OpenWiki claim record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_facts",
    title: "List OpenWiki Facts",
    description: "List policy-visible fact records with optional status, kind, and reference filters.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        statuses: { type: "array", items: { type: "string", enum: ["active", "stale", "disputed", "forgotten", "archived"] } },
        kinds: { type: "array", items: { type: "string" } },
        subject_ids: { type: "array", items: { type: "string" } },
        page_ids: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        claim_ids: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 0, maximum: 500 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_fact",
    title: "Read OpenWiki Fact",
    description: "Read an OpenWiki fact record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_takes",
    title: "List OpenWiki Takes",
    description: "List policy-visible take records with optional status and reference filters.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        statuses: { type: "array", items: { type: "string", enum: ["open", "resolved", "archived"] } },
        page_ids: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        claim_ids: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 0, maximum: 500 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_take",
    title: "Read OpenWiki Take",
    description: "Read an OpenWiki take record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.takes_scorecard",
    title: "Score OpenWiki Takes",
    description: "Return deterministic Brier-score aggregates for policy-visible resolved takes.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.find_trajectory",
    title: "Find OpenWiki Trajectory",
    description: "Return a deterministic timeline for a record ID or query across visible facts, takes, claims, proposals, and events.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string" },
        query: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 500 },
        order: { type: "string", enum: ["asc", "desc"] },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_proposals",
    title: "List OpenWiki Proposals",
    description: "List OpenWiki proposals, optionally filtered by status, actor, target, section, or update time.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        statuses: { type: "array", items: { type: "string", enum: ["open", "accepted", "rejected", "applied", "closed"] } },
        actor_id: { type: "string" },
        target_id: { type: "string" },
        target_path: { type: "string" },
        section_id: { type: "string" },
        updated_after: { type: "string" },
        limit: { type: "integer", minimum: 0, maximum: 200 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_proposal",
    title: "Read OpenWiki Proposal",
    description: "Read an OpenWiki proposal record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_proposal_detail",
    title: "Read OpenWiki Proposal Detail",
    description: "Read an OpenWiki proposal with diff, snapshot, and validation report artifacts.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.read_decision",
    title: "Read OpenWiki Decision",
    description: "Read an OpenWiki decision record by ID or URI.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.trace_claim",
    title: "Trace OpenWiki Claim",
    description: "Return a claim with its page and supporting sources.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: { id: { type: "string", minLength: 1 } },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.get_history",
    title: "Get OpenWiki History",
    description: "Return Git commit history for an OpenWiki record.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.diff_versions",
    title: "Diff OpenWiki Versions",
    description: "Return a Git diff for an OpenWiki record.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        from: { type: "string" },
        to: { type: "string" },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_recent_changes",
    title: "List OpenWiki Recent Changes",
    description: "Return recent Git commits and changed files.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.git_status",
    title: "Read OpenWiki Git Remote Status",
    description: "Return branch, upstream, remote, ahead/behind, and dirty working tree status for the OpenWiki Git repository.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 500 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_events",
    title: "List OpenWiki Events",
    description: "Return durable OpenWiki audit events.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 200 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_runs",
    title: "List OpenWiki Runs",
    description: "Return durable OpenWiki job run records.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 200 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.dream_status",
    title: "Read OpenWiki Dream Runs",
    description: "Return recent OpenWiki dream-cycle run records or one dream run by ID.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        run_id: { type: "string" },
        limit: { type: "integer", minimum: 1, maximum: 200 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_topics",
    title: "List OpenWiki Topics",
    description: "Return topic summaries derived from OpenWiki pages.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 500 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_open_questions",
    title: "List OpenWiki Open Questions",
    description: "Return open questions extracted from OpenWiki pages.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  ...READ_INBOX_TOOL_DEFINITIONS,
  {
    name: "wiki.detect_governance",
    title: "Run OpenWiki Governance Detectors",
    description: "Return permission-filtered findings for stale claims, missing sources, broken links, and orphan pages.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        detectors: {
          type: "array",
          items: { type: "string", enum: ["stale_claim", "missing_source", "broken_link", "orphan_page"] },
        },
        stale_after_days: { type: "integer", minimum: 1, maximum: 3650 },
      },
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_neighbors",
    title: "Read OpenWiki Graph Neighbors",
    description: "Return graph nodes and edges around a page, source, claim, proposal, decision, topic, or section.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        direction: { type: "string", enum: ["in", "out", "both"] },
        depth: { type: "integer", minimum: 1, maximum: 3 },
        limit: { type: "integer", minimum: 1, maximum: 500 },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_backlinks",
    title: "Read OpenWiki Graph Backlinks",
    description: "Return inbound graph edges for a record or synthetic graph node.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 500 },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_related",
    title: "Read OpenWiki Related Graph",
    description: "Return directly and topically related graph context for a record.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        limit: { type: "integer", minimum: 1, maximum: 200 },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_path",
    title: "Find OpenWiki Graph Path",
    description: "Find a permission-filtered graph path between two records.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        from_id: { type: "string", minLength: 1 },
        to_id: { type: "string", minLength: 1 },
      },
      required: ["from_id", "to_id"],
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_orphans",
    title: "List OpenWiki Graph Orphans",
    description: "Return visible pages that have no page-to-page graph links.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_stale",
    title: "List OpenWiki Stale Graph Nodes",
    description: "Return visible pages and claims that need graph or evidence maintenance.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.graph_report",
    title: "Read OpenWiki Graph Report",
    description: "Return deterministic graph intelligence over the permission-filtered OpenWiki graph.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
    },
    annotations: { readOnlyHint: true },
  },
];
