import { PROPOSAL_INBOX_TOOL_DEFINITIONS } from "./inbox-tool-definitions.ts";

export const PROPOSAL_TOOL_DEFINITIONS = [
  {
    name: "wiki.propose_edit",
    title: "Propose OpenWiki Edit",
    description: "Create an auditable proposal for a page body change without mutating the canonical page.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        page_id: { type: "string", minLength: 1 },
        body: { type: "string", minLength: 1 },
        title: { type: "string" },
        summary: { type: "string" },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["page_id", "body"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_synthesis",
    title: "Propose OpenWiki Synthesis Page",
    description: "Create an auditable proposal for a new synthesis page without mutating the canonical wiki.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", minLength: 1 },
        body: { type: "string", minLength: 1 },
        page_type: { type: "string" },
        summary: { type: "string" },
        topics: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["title", "body"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_source",
    title: "Propose OpenWiki Source",
    description: "Create an auditable proposal for a new source manifest without mutating canonical sources.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", minLength: 1 },
        source_type: { type: "string" },
        url: { type: "string" },
        content_hash: { type: "string" },
        actor_id: { type: "string" },
        rationale: { type: "string" },
        retrieved_at: { type: "string" },
        trust: { type: "object" },
      },
      required: ["title"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_fact",
    title: "Propose OpenWiki Fact",
    description: "Create an auditable proposal for a new fact without mutating the canonical facts ledger.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string" },
        kind: { type: "string" },
        text: { type: "string", minLength: 1 },
        subject_ids: { type: "array", items: { type: "string" } },
        page_ids: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        claim_ids: { type: "array", items: { type: "string" } },
        confidence: { type: "string", enum: ["low", "medium", "high"] },
        sensitivity: { type: "string", enum: ["public", "internal", "private"] },
        status: { type: "string", enum: ["active", "stale", "disputed", "forgotten", "archived"] },
        valid_from: { type: "string" },
        valid_to: { type: "string" },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["text"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_take",
    title: "Propose OpenWiki Take",
    description: "Create an auditable proposal for a new probabilistic take without mutating the canonical takes ledger.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string" },
        statement: { type: "string", minLength: 1 },
        rationale: { type: "string" },
        proposal_rationale: { type: "string" },
        probability: { type: "number", minimum: 0, maximum: 1 },
        confidence: { type: "string", enum: ["low", "medium", "high"] },
        status: { type: "string", enum: ["open", "resolved", "archived"] },
        due_at: { type: "string" },
        page_ids: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        claim_ids: { type: "array", items: { type: "string" } },
        actor_id: { type: "string" },
      },
      required: ["statement"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.resolve_take",
    title: "Resolve OpenWiki Take",
    description: "Create an auditable proposal that resolves an existing take and records its scoring outcome.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        resolution: { type: "string", enum: ["correct", "incorrect", "partial", "unresolvable"] },
        resolved_at: { type: "string" },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["id", "resolution"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.forget_fact",
    title: "Forget OpenWiki Fact",
    description: "Create an auditable proposal that marks a fact forgotten in the canonical ledger; it does not rewrite Git history.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        id: { type: "string", minLength: 1 },
        valid_to: { type: "string" },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["id"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.comment_on_proposal",
    title: "Comment On OpenWiki Proposal",
    description: "Append a non-decision comment to an OpenWiki proposal.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        proposal_id: { type: "string", minLength: 1 },
        body: { type: "string", minLength: 1 },
        actor_id: { type: "string" },
      },
      required: ["proposal_id", "body"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.dream_run",
    title: "Run OpenWiki Dream Cycle",
    description: "Queue or execute the OpenWiki dream cycle in dry-run/report mode, optionally creating review proposals when wait=true and create_proposals=true.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        phases: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "lint",
              "index_refresh",
              "stale_claims",
              "missing_backlinks",
              "thin_pages",
              "orphan_pages",
              "link_suggestions",
              "fact_candidates",
              "take_score_candidates",
              "report",
            ],
          },
        },
        limit: { type: "integer", minimum: 1, maximum: 200 },
        timeout_ms: { type: "integer", minimum: 1000, maximum: 300000 },
        dry_run: { type: "boolean" },
        create_proposals: { type: "boolean" },
        provider: { type: "string" },
        schema_pack: { type: "string" },
        actor_id: { type: "string" },
        wait: { type: "boolean" },
      },
    },
    annotations: { readOnlyHint: false },
  },
  ...PROPOSAL_INBOX_TOOL_DEFINITIONS,
];
