import { SOURCE_FETCH_CONNECTOR_KINDS } from "@openwiki/connectors";
import { WRITE_INBOX_TOOL_DEFINITIONS } from "./inbox-tool-definitions.ts";

export const WRITE_TOOL_DEFINITIONS = [
  {
    name: "wiki.read_policy",
    title: "Read OpenWiki Policy",
    description: "Return Git-backed section, grant, and approval-rule policy. Requires admin scope.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.list_workspaces",
    title: "List OpenWiki Workspaces",
    description: "Return the current workspace registry with organization, tenant, workspace, and repo records. Requires admin scope.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: true },
  },
  {
    name: "wiki.connect_workspace",
    title: "Connect OpenWiki Workspace",
    description: "Configure the current workspace Git remote metadata using deployment-managed credential_ref auth. Requires admin scope.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        remote: { type: "string" },
        branch: { type: "string" },
        remote_url: { type: "string" },
        credential_ref: { type: "string" },
      },
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_policy",
    title: "Propose OpenWiki Policy Change",
    description: "Create an auditable proposal to replace one Git-backed policy JSON file. Requires admin scope.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        policy_file: { type: "string", enum: ["sections", "grants", "approval-rules", "approval_rules"] },
        body: { type: "string", minLength: 1 },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["policy_file", "body"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.propose_section_policy",
    title: "Propose OpenWiki Section Policy",
    description: "Create one auditable proposal that adds or updates a section, grants, and approval rule. Requires admin scope.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        section_id: { type: "string", minLength: 1 },
        title: { type: "string", minLength: 1 },
        paths: { type: "array", items: { type: "string" }, minItems: 1 },
        visibility: { type: "string", enum: ["public", "internal", "private"] },
        owner_principal: { type: "string" },
        viewer_principals: { type: "array", items: { type: "string" } },
        contributor_principals: { type: "array", items: { type: "string" } },
        researcher_principals: { type: "array", items: { type: "string" } },
        reviewer_principals: { type: "array", items: { type: "string" } },
        maintainer_principals: { type: "array", items: { type: "string" } },
        admin_principals: { type: "array", items: { type: "string" } },
        required_reviewer_principals: { type: "array", items: { type: "string" } },
        actor_id: { type: "string" },
        rationale: { type: "string" },
      },
      required: ["section_id", "title", "paths"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.ingest_source",
    title: "Ingest OpenWiki Source",
    description: "Create a source manifest and optional raw text capture in the OpenWiki repository.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", minLength: 1 },
        source_type: { type: "string" },
        url: { type: "string" },
        content: { type: "string" },
        actor_id: { type: "string" },
      },
      required: ["title"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.fetch_source",
    title: "Fetch OpenWiki Source",
    description:
      "Queue a bounded HTTP, GitHub, or GitLab source fetch that ingests fetched content through OpenWiki source policy. Set wait=true to execute inline.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", minLength: 1 },
        url: { type: "string", minLength: 1 },
        source_type: { type: "string" },
        connector_kind: { type: "string", enum: [...SOURCE_FETCH_CONNECTOR_KINDS] },
        connector_id: { type: "string" },
        credential_ref: { type: "string" },
        github_owner: { type: "string" },
        github_repo: { type: "string" },
        gitlab_project: { type: "string" },
        source_path: { type: "string" },
        ref: { type: "string" },
        actor_id: { type: "string" },
        max_bytes: { type: "integer", minimum: 1 },
        timeout_ms: { type: "integer", minimum: 1 },
        wait: { type: "boolean" },
      },
      required: ["title"],
    },
    annotations: { readOnlyHint: false },
  },
  ...WRITE_INBOX_TOOL_DEFINITIONS,
  {
    name: "wiki.review_proposal",
    title: "Review OpenWiki Proposal",
    description: "Record a proposal review decision.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        proposal_id: { type: "string", minLength: 1 },
        decision: { type: "string", enum: ["accepted", "rejected", "needs_changes"] },
        rationale: { type: "string", minLength: 1 },
        actor_id: { type: "string" },
      },
      required: ["proposal_id", "decision", "rationale"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.close_proposal",
    title: "Close OpenWiki Proposal",
    description: "Close a proposal, optionally marking it superseded by another proposal.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        proposal_id: { type: "string", minLength: 1 },
        rationale: { type: "string", minLength: 1 },
        resolution: { type: "string", enum: ["closed", "superseded", "withdrawn", "duplicate", "stale", "invalid"] },
        superseded_by: { type: "string" },
        actor_id: { type: "string" },
      },
      required: ["proposal_id", "rationale"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.apply_proposal",
    title: "Apply OpenWiki Proposal",
    description: "Apply an accepted proposal snapshot to the canonical page.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        proposal_id: { type: "string", minLength: 1 },
        actor_id: { type: "string" },
      },
      required: ["proposal_id"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.create_synthesis",
    title: "Create OpenWiki Synthesis Page",
    description: "Create, review, and apply a synthesis page through the governed proposal workflow.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string", minLength: 1 },
        body: { type: "string", minLength: 1 },
        page_type: { type: "string" },
        summary: { type: "string" },
        topics: { type: "array", items: { type: "string" } },
        source_ids: { type: "array", items: { type: "string" } },
        actor_id: { type: "string" },
        rationale: { type: "string" },
        decision_rationale: { type: "string" },
        commit: { type: "boolean" },
        message: { type: "string" },
      },
      required: ["title", "body"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.run_job",
    title: "Run OpenWiki Local Job",
    description: "Queue a trusted OpenWiki job such as index rebuild, static export, Git sync, backup, source fetch, or lint. Set wait=true to execute inline.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        run_type: { type: "string", enum: ["index.rebuild", "static.export", "lint", "source.fetch", "git.sync", "backup.create", "inbox.process", "inbox.reconcile"] },
        actor_id: { type: "string" },
        input: { type: "object" },
        wait: { type: "boolean" },
      },
      required: ["run_type"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.run_lint",
    title: "Lint OpenWiki Repository",
    description: "Run deterministic OpenWiki repository validation without queueing a job.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {},
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.commit_changes",
    title: "Commit OpenWiki Changes",
    description:
      "Commit staged or selected OpenWiki-managed Git changes and append an audit event. Use all=true to stage OpenWiki-managed paths.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        message: { type: "string", minLength: 1 },
        actor_id: { type: "string" },
        paths: { type: "array", items: { type: "string" } },
        all: { type: "boolean" },
      },
      required: ["message"],
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.git_pull",
    title: "Pull OpenWiki Git Remote",
    description: "Fast-forward pull from the configured OpenWiki Git remote. Fails when the workspace has uncommitted changes.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        remote: { type: "string" },
        branch: { type: "string" },
      },
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.git_push",
    title: "Push OpenWiki Git Remote",
    description: "Push HEAD to the configured OpenWiki Git remote branch. Fails when the workspace has uncommitted changes.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        remote: { type: "string" },
        branch: { type: "string" },
      },
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.sync_now",
    title: "Sync OpenWiki Git Remote",
    description: "Run safe Git sync through OpenWiki coordination. Defaults to pull then push, refuses dirty workspaces, and never commits changes.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        pull: { type: "boolean" },
        push: { type: "boolean" },
        remote: { type: "string" },
        branch: { type: "string" },
        actor_id: { type: "string" },
      },
    },
    annotations: { readOnlyHint: false },
  },
  {
    name: "wiki.publish",
    title: "Publish OpenWiki Static Site",
    description: "Publish derived OpenWiki static artifacts and record a publish.completed event.",
    inputSchema: {
      type: "object",
      additionalProperties: false,
      properties: {
        out_dir: { type: "string" },
        base_url: { type: "string" },
        actor_id: { type: "string" },
      },
    },
    annotations: { readOnlyHint: false },
  },
];
