export const COMMAND_PALETTE_SHORTCUT = 'CmdOrCtrl+Shift+P'
export const CAPABILITIES_SHORTCUT = 'CmdOrCtrl+Shift+C'
export const AGENTS_SHORTCUT = 'CmdOrCtrl+Shift+A'
export const SEARCH_THREADS_SHORTCUT = 'CmdOrCtrl+K'
export const NEW_THREAD_SHORTCUT = 'CmdOrCtrl+N'
export const SETTINGS_SHORTCUT = 'CmdOrCtrl+,'
